### ISSUE TITLE
Unable to download problemset

### ISSUE THREAD

**Issue by gaddevarunteja** [dipu-bd/UVA-Arena#28]
I cant find whether the problems are downloaded or not.
It is not showing any problem in problem list but at the bottom of the window continuously it is showing downloaded problem list

**Comment by dipu-bd** [comment]
Right click on the problem list and click Refresh. 
This problem should be fixed in version 1.6.1. [Download](http://www.mediafire.com/download/kh7he74cceuxu3j/UVA_Arena_1.6.1.exe) and install it again. It may solve your issue.
If this does not work, check the log.dat file inside "Documents\UVA Arena" folder and message it to the [facebook support group](https://www.facebook.com/uvaarena).

**Comment by gaddevarunteja** [comment]
I clicked to update to version 1.6.1 but it says application not found. Also I am not able to download from the given link.

**Comment by dipu-bd** [comment]
Try one of the link here- https://github.com/dipu-bd/UVA-Arena

**Comment by gaddevarunteja** [comment]
Where can I find problem list?

**Comment by dipu-bd** [comment]
Problem list are automatically downloaded. To download them manually click on **Update List** button at the top-left corner of the **Problems** tabpage. 
DId you install version 1.6.1?

**Comment by gaddevarunteja** [comment]
I have downloaded.it is working.

**Comment by gaddevarunteja** [comment]
what should we do if we want to download only pdf files not images and other?

**Comment by dipu-bd** [comment]
There is currently no option like this. Both HTML and PDF gets downloaded. You can download the big version of UVA Arena setup to get all problem descriptions in one go.
