### ISSUE TITLE
Code compilation failed for c++ using mingw.

### ISSUE THREAD

**Issue by nocmnt** [dipu-bd/UVA-Arena#29]
![image](https://cloud.githubusercontent.com/assets/11255780/13014984/b0d7718a-d1e0-11e5-8049-1fcd3a3bcf49.png)

**Comment by mumhero** [comment]
Did you add the path of MinGW bin directory to PATH environment variable? Otherwise mingw32-g++.exe can't find as.exe and ld.exe, which is used to produce execute file.

Maybe we can set the working directory of mingw32-g++.exe process to MinGW bin directory in code, so user doesn't need to set environment variable anymore.

**Comment by dipu-bd** [comment]
I have not tested it for CodeBlocks v16 yet. I will look into it the first chance I get. Thanks for informing me.

**Comment by SRITANU** [comment]
I am also facing the same issue.Any updates?
